data:
  dataset: darcy_1d
dimensions: 1
resolution: 128
source_channels: 1
target_channels: 1
device: cuda
mode: direct
model: fno
fno:
  n_lifting_channels: 256
  n_hidden_channels: 256
  n_layers: 4
  n_projection_channels: 256
  n_time_embedding_dim: 256
  separable: True
  skip_type: soft-gating
  n_modes:
    - 64
  norm_type: group
  factorisation_rank: 1
  factorisation_type: ComplexDense
  fft_norm: ortho
  mlp_dropout: 0.1
  mlp_expansion: 4
interpolate:
  b: 0.01
noise:
  gain: 1.0
  len: 1.0
training:
  n_epochs: 12000
  n_batch: 250
  grad_clip: 1.0
  lr: 1e-4
  n_warmup_steps: 500
  n_cosine_cycle_steps: 50000
  n_ema_half_life_steps: 69
sampling:
  n_t_steps: 100
  start_t: 0.0
  end_t: 1.0
  c: 1.0
  use_pc: true  # whether to use predictor-corrector

# means: tensor([3.8022e-04, 5.6180e-05])
# stds: tensor([1.0008, 0.1469])
# (source s, pressure u)