data:
  dataset: darcy
dimensions:
  - 128
  - 128
source_channels: 1
target_channels: 1
device: cuda
fno:
  n_lifting_channels: 32
  n_hidden_channels: 32
  n_layers: 4
  n_projection_channels: 32
  n_time_embedding_dim: 32
  separable: True
  skip_type: soft-gating
  n_modes:
    - 64
    - 64
  norm_type: group
  factorisation_rank: 1
  factorisation_type: ComplexDense
  fft_norm: ortho
  mlp_dropout: 0.1
  mlp_expansion: 4
interpolate:
  b: 0.5
noise:
  gain: 1.0
  len: 1.0
training:
  n_epochs: 12000
  n_batch: 250
  grad_clip: 1.0
  lr: 2e-5
  n_warmup_steps: 5000
  n_cosine_cycle_steps: 5000
sampling:
  n_t_steps: 50
  start_t: 0
  end_t: 1
  c: 1.0
model: 
  mode: separate