data:
  dataset: darcy_1d
dimension: 128
device: cuda
fno:
  n_lifting_channels: 256
  n_hidden_channels: 256
  n_layers: 4
  n_in_channels: 2
  n_out_channels: 2
  n_projection_channels: 256
  n_time_embedding_dim: 256
  separable: True
  skip_type: soft-gating
  n_modes:
    - 32
  norm_type: group
  factorisation_rank: 1
  factorisation_type: ComplexDense
  fft_norm: ortho
  mlp_dropout: 0.1
  mlp_expansion: 4
interpolate:
  eps: 0.005
noise:
  gain: 1.0
  len: 1.0
training:
  n_epochs: 12000
  n_batch: 250
  grad_clip: 1.0
  lr: 1e-4
sampling:
  n_t_steps: 1000
  start_t: 0.0
  end_t: 1
